Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

Project/main/urls.py
from django.urls import path
from . import views

urlpatterns = [


    path('contact/', views.contact_view, name='contact'),
    path('insert', views.insert, name='insert'),
    path('success', views.success_view, name='success'),
    path('', views.news, name='news'),
]

Project/main/models.py
from django.db import models

# Create your models here.

class News(models.Model):
     title = models.CharField('Названия', max_length=80)
     name = models.CharField('Name',max_length=80, blank=False)
     surname = models.CharField('Surname',max_length=80, blank=False)
     news=models.TextField('Описания',blank=False)
     is_published = models.BooleanField(default=True)
     id = models.IntegerField( unique=True, db_index=True, verbose_name="URL",primary_key=True)
     time_create = models.DateTimeField(auto_now_add=True)
     def __str__(self):
         return self.title

Project/main/forms.py
from .models import *
from django.forms import ModelForm
from django import forms


class NewsForm(ModelForm):
    class Meta:
        model = News
        fields = "__all__"
class ContactForm(forms.Form):
    from_email = forms.EmailField(label='Email', required=True)
    subject = forms.CharField(label='About', required=True)
    message = forms.CharField(label='Message', widget=forms.Textarea, required=True)

Project/main/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import redirect

from django.shortcuts import render

from .forms import *

def contact_view(request):
    if request.method == 'GET':
        form = ContactForm()
    elif request.method == 'POST':
        # если метод POST, проверим форму и отправим письмо
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(f'{subject} от {from_email}', message,
                          '200103346@stu.sdu.edu.kz',
                          [f'{from_email}'], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Ошибка в теме письма.')
            return redirect('success')
    else:
        return HttpResponse('Неверный запрос.')
    return render(request, "main/sendMessage.html", {'form': form})
def success_view(request):
    return HttpResponse('Приняли! Спасибо за вашу заявку.')

def insert(request):
    error = ''
    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/news')
        else:
            error = 'Форма была неверной'

    form = NewsForm()
    data = {
        'form': form,
        'error': error
    }
    return render(request, 'main/insert.html', data)


def news(request):
    new = News.objects.order_by('-id')
    return render(request, 'main/viewsNews.html', {'news': new})

Project/main/templates/main/insert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    #id_title{
    width:500px;
    background: #FFFFFF;
border: 1px solid #C8C8C8;
box-shadow: inset 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 21px;
    }
    #id_news{
    background: #FFFFFF;
border: 1px solid #C8C8C8;
box-shadow: inset 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 21px;
    width:500px;
    }
</style>
</head>
<body>
<div align="center" class="features">
    <h1>Жаңалықтарды енгізу</h1>
    <form method="post">
        {% csrf_token %}
        <p style="width:300px"> {{ form.as_p }}</p><br>

        <span>{{ error }}</span>
        <button style="width:500px" type="submit" class="btn btn-primary">Қосу</button>
    </form>
</div>
</body>
</html>

Project/main/templates/main/sendMessage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    #id_from_email{

    width:450px;
    background: #FFFFFF;
border: 1px solid #C8C8C8;
box-shadow: inset 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 21px;


    }
    #id_subject{
    background: #FFFFFF;
border: 1px solid #C8C8C8;
box-shadow: inset 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 21px;
    width:450px;
    }
    #id_message{
      background: #FFFFFF;
border: 1px solid #C8C8C8;
box-shadow: inset 0px 4px 4px rgba(0, 0, 0, 0.25);
border-radius: 21px;
    width:500px;
    }
</style>
</head>
<body>
<div align="center"><img src="https://avatars.mds.yandex.net/i?id=4086a27e0726a9bdab6eae7c7d78808f-5875850-images-thumbs&n=13&exp=1"></div>
<div style="margin-top:100px;">



    <div align="center">

<h1 style="
font-family: 'Mulish';
font-style: normal;
margin-bottom:50px;
line-height: 19px;" class="text-center">Отправкa сообщений</h1>

      <form method="post">
        {% csrf_token %}

          <p> <h5>Email</h5>{{ form.from_email}}</p><br>
          <p><h5>subject</h5>{{ form.subject}}</p><br>
          <h5>Content</h5>
        {{ form.message}}
        <div  class="form-actions form-group ">
          <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
      </form>
    </div>
     </div>

    </div>
</body>
</html>

Project/main/templates/main/viewsNews.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for el in news %}
<div  style="border-radius:21px;width:95%"  class="p-3= mb-2 bg-primary text-white text-center">
         <br> <h3>{{ el.title }}</h3> <br>
                <p>{{ el.name}}</p>
                <p>{{ el.surname }}</p>
                <p>{{ el.news }}</p>
                <p>{{ el.is_published }}</p>
                <p>{{ el.time_create}}</p>
                <p>{{ el.id}}</p>
    {%endfor%}
</div>
</body>
</html>